# Generated by Django 4.2.3 on 2023-07-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_state_listing_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='size',
        ),
    ]
